project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  arxiv-pdf: default
  # you cannot have multiple pdfs at once apparently when try and render
  #nature-pdf: default




